# Generated by Django 4.2.29 on 2026-03-20 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_application_status_rating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="application",
            unique_together=set(),
        ),
    ]
