# Generated by Django 4.2.29 on 2026-03-26 05:03

from django.db import migrations, models
import django.db.models.deletion

def backfill_legacy_contracts(apps, schema_editor):
    Application = apps.get_model('jobs', 'Application')
    ApplicationContract = apps.get_model('jobs', 'ApplicationContract')
    for app in Application.objects.filter(status__in=('hired', 'completed')):
        ApplicationContract.objects.get_or_create(
            application=app,
            defaults={
                'contract_status': 'complete',
                'worker_accepted_terms': True,
                'worker_accepted_at': app.hired_at,
                'employer_confirmed_at': app.hired_at,
            },
        )


def noop_reverse(apps, schema_editor):
    pass




class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_application_hired_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("employer_uploaded", "Employer uploaded"),
                            ("worker_responded", "Worker responded"),
                            ("complete", "Complete"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                (
                    "employer_contract_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="application_contracts/employer/",
                    ),
                ),
                (
                    "worker_signed_file",
                    models.FileField(
                        blank=True, null=True, upload_to="application_contracts/worker/"
                    ),
                ),
                ("worker_accepted_terms", models.BooleanField(default=False)),
                ("worker_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("employer_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("contract_sent_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="jobs.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RunPython(backfill_legacy_contracts, noop_reverse),
    ]
