# Generated by Django 4.2

from django.db import migrations, models


def forwards_skills(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.all().only('id', 'required_skills'):
        raw = job.required_skills or []
        new_list = []
        changed = False
        for item in raw:
            if isinstance(item, str):
                new_list.append({'skill': item, 'years_experience': None})
                changed = True
            elif isinstance(item, dict) and item.get('skill'):
                new_list.append(
                    {
                        'skill': item['skill'],
                        'years_experience': item.get('years_experience'),
                    }
                )
            else:
                changed = True  # drop invalid entries
        if changed or raw != new_list:
            job.required_skills = new_list
            job.save(update_fields=['required_skills'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0005_application_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='positions_needed',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='auto_closed_when_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='employer_acknowledged_vacancy_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(forwards_skills, noop_reverse),
    ]
