# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0006_job_post_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rate_type',
            field=models.CharField(
                choices=[('daily', 'Daily'), ('monthly', 'Monthly')],
                default='daily',
                max_length=20,
            ),
        ),
    ]
