# Generated by Django 4.2.29 on 2026-04-12 10:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_job_rate_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="positions_needed",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="ApplicationSkillRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_ratings",
                        to="jobs.application",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="applicationskillrating",
            constraint=models.UniqueConstraint(
                fields=("application", "skill_name"),
                name="uniq_application_skill_rating",
            ),
        ),
    ]
