# Generated by Django 4.2.29 on 2026-03-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employerprofile",
            name="doc_url",
        ),
        migrations.RemoveField(
            model_name="employerprofile",
            name="verified",
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="doc_barangay_clearance",
            field=models.FileField(blank=True, upload_to="employer_docs/"),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="doc_bir",
            field=models.FileField(blank=True, upload_to="employer_docs/"),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="doc_employer_registrations",
            field=models.FileField(blank=True, upload_to="employer_docs/"),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="doc_mayors_permit",
            field=models.FileField(blank=True, upload_to="employer_docs/"),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="doc_sec_dti",
            field=models.FileField(blank=True, upload_to="employer_docs/"),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="not_submitted",
                max_length=20,
            ),
        ),
    ]
