# Generated by Django 4.2.29 on 2026-03-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_employerprofile_doc_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="doc_nbi_clearance",
            field=models.FileField(blank=True, upload_to="worker_docs/"),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="national_id_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="national_id_status",
            field=models.CharField(
                choices=[
                    ("not_verified", "Not Verified"),
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("failed", "Failed"),
                ],
                default="not_verified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="not_submitted",
                max_length=20,
            ),
        ),
    ]
