# Generated by Django 4.2.29 on 2026-03-23 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_workerprofile_doc_nbi_clearance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signup_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sms_outreach", "SMS Outreach"),
                    ("facebook_group", "Facebook Group"),
                    ("referral", "Referral"),
                    ("job_fair", "Job Fair"),
                    ("direct", "Direct"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("signup", "Signed Up"),
                            ("profile_completed", "Profile Completed"),
                            ("job_posted", "Job Posted"),
                            ("job_applied", "Applied to Job"),
                            ("application_viewed", "Application Viewed"),
                            ("shortlisted", "Shortlisted"),
                            ("hired", "Hired"),
                            ("completed", "Job Completed"),
                            ("rated", "Rating Given"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="accounts_ac_action_0ce76e_idx",
                    ),
                    models.Index(
                        fields=["user", "action"], name="accounts_ac_user_id_bfb4b4_idx"
                    ),
                ],
            },
        ),
    ]
