# Generated by Django 4.2.29 on 2026-03-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_signup_source_activitylog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="signup_source",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name="ActivityLog",
        ),
    ]
