# Generated by Django 4.2.29 on 2026-03-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("non_binary", "Non-binary"),
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("self_describe", "Self-describe"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="languages_known",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("separated", "Separated"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="nationality",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="religion",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
