# Generated by Django 4.2.29 on 2026-04-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_workerprofile_biodata"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerPortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("caption", models.TextField(blank=True, default="")),
                (
                    "related_skill",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("photo", models.ImageField(upload_to="worker_portfolio/")),
                (
                    "proof_file",
                    models.FileField(blank=True, upload_to="worker_portfolio/"),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "worker_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="accounts.workerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker portfolio item",
                "verbose_name_plural": "Worker portfolio items",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
